### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AlexanderTirik** [AlexanderTirik/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by TirikAlexander** [comment]
June 28, 1971: Born in Pretoria, South Africa 
Musk was born on June 28, 1971, in Pretoria, South Africa. He is the son of Maye Musk, a model and dietitian from Regina, Saskatchewan, Canada, and Errol Musk, a South African electromechanical engineer, pilot and sailor.

1980: Parents Divorce    
His parents were divorced in 1980.

1981: Interest in Computing   
At the age of 10, he developed an interest in computing with the Commodore VIC-20 and taught himself computer programming. 

1983: Sold his first video game, Blastar          
By the age of 12, Musk sold the code of a BASIC-based video game he created called Blastar, to a magazine called PC and Office Technology, for approximately $500.

June 1989: Moved to Canada to attend Queen's University        
At the age of 17, in June 1989, Elon Musk moved to Canada to attend Queen's University, avoiding mandatory service in the South African military. His plan was to go United States where he thought great things are possible, more than any other country. And it would be easy to get to the United States from Canada.

1992: Went to University of Pennsylvania to Study Business and Physics          
He left Queen's University in 1992 to study business and physics at the University of Pennsylvania, and graduated with an undergraduate degree in economics and stayed for a second bachelor's degree in physics.

1995: Started Zip2, a Web Software Company  
In 1995, Musk and his brother, Kimbal, started Zip2, a web software company which developed and marketed an Internet city guide for the newspaper publishing industry. The company raised  money from a small group of angel investors.

February 1999: Sold Zip2 to Compaq for US$307 million      
Compaq acquired Zip2 for US$307 million in cash and US$34 million in stock options in February 1999. Musk received US$22 million for his 7 percent share from the sale.

March 1999: Cofounded X.com, a financial service and payment company   
In March 1999, Musk co-founded X.com, an online financial services and e-mail payment company, with US$10 million from the sale of Zip2.

2000: X.com merged with Confinity to form PayPal, Musk married his first wife
X.com merged with Confinity, which had a money-transfer service called PayPal and Musk became the CEO and company's largest shareholder by owning 11.7% of shares. The merged company focused on the PayPal service and was later renamed PayPal. PayPal's early growth was driven mainly by a viral marketing campaign where new customers were recruited when they received money through the service.
Musk met his first wife, Canadian author Justine Wilson, while both were students at Ontario's Queen's University. They married in 2000. Their first son, Nevada Alexander Musk, died of sudden infant death syndrome (SIDS) at the age of 10 weeks.

October 2000: Musk got Fired from PayPal 
Musk was ousted in October 2000 from his role as CEO of PayPal (although he remained on the board) due to disagreements with other company leadership, notably over his desire to move PayPal's Unix-based infrastructure to Microsoft Windows. 

2001: Interest in Space Exploration       
In 2001, Musk conceptualized Mars Oasis, a project to land a miniature experimental greenhouse on Mars, containing food crops growing on Martian regolith, in an attempt to regain public interest in space exploration. 

October 2001: Went to Moscow to buy ICBMs to send payloads to Mars  
In October 2001, Musk travelled to Moscow with Jim Cantrell (an aerospace supplies fixer), and Adeo Ressi (his best friend from college), to buy refurbished Dnepr Intercontinental ballistic missiles (ICBMs) that could send the envisioned payloads into space. The group met with companies such as NPO Lavochkin and Kosmotras; however, according to Cantrell, Musk was seen as a novice and was consequently spat on by one of the Russian chief designers, and the group returned to the United States empty-handed 

February 2002: Got an idea to build affordable Rockets    
In February 2002, the group returned to Russia to look for three ICBMs, bringing along Mike Griffin. Griffin had worked for the CIA's venture capital arm, In-Q-Tel, as well as NASA's Jet Propulsion Laboratory, and was just leaving Orbital Sciences, a maker of satellites and spacecraft. The group met again with Kosmotras, and were offered one rocket for US$8 million; however, this was seen by Musk as too expensive; Musk consequently stormed out of the meeting. On the flight back from Moscow, Musk realized that he could start a company that could build the affordable rockets he needed.

May 2002: Founded SpaceX, a space exploration company    
Musk founded Space Exploration Technologies, or SpaceX, in May 2002 with US$100 million of his early fortune. Musk became the chief executive officer (CEO) and chief technology officer (CTO). SpaceX develops and manufactures space launch vehicles with a focus on advancing the state of rocket technology. 

October 2002: eBay acquired PayPal
In October 2002, PayPal was acquired by eBay for US$1.5 billion in stock, of which Musk received US$165 million. 

July 2003: Tesla, Inc was incorporated
Tesla, Inc. (originally Tesla Motors) was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning, who financed the company until the Series A round of funding.

2004: Musk's wife gave birth to twin sons
Musk and his wife had 2 sons, twins, through in vitro fertilization. 

February 2004: Musk joined Tesla
Musk led the Series A round of investment for Tesla in February 2004, joined Tesla's board of directors as its chairman. 

2006: Musk's wife gave birth to triplets, Cofounded SolarCity and SpaceX Success
Musk and his wife had other 3 sons, triplets, through in vitro fertilization.
Musk provided the initial concept and financial capital for SolarCity, which was then co-founded in 2006 by his cousins Lyndon and Peter Rive.
From 2006, SpaceX got various contracts from NASA to transport cargo and astronauts to the International Space Station.

2007: Musk became the CEO of Tesla
Following the financial crisis in 2008 and after a series of escalating conflicts in 2007, Eberhard was ousted from the firm. Musk assumed leadership of the company as CEO and product architect.

2008: Musk and Wife, Justine Separated
Musk and his wife Justine were separated. They share custody of their five sons.

2010: Musk married his second wife, Talulah Riley
In 2008, Musk began dating English actress Talulah Riley, and in 2010, the couple married. In January 2012, Musk announced that he had ended his four-year relationship with Riley, tweeting to Riley, "It was an amazing four years. I will love you forever. You will make someone very happy one day." In July 2013, Musk and Riley remarried. In December 2014, Musk filed for a second divorce from Riley; however, the action was withdrawn. The media announced in March 2016 that divorce proceedings were again under way, this time with Riley filing for divorce from Musk. The divorce was finalized in late 2016.

2010: Donated a 25-kW Solar power system          
In 2010, the Musk Foundation collaborated with SolarCity to donate a 25-kW solar power system to the South Bay Community Alliance's hurricane response center in Coden, Alabama.

2011: Expressed his hope to send human to Mars          
In a 2011 interview, he said he hopes to send humans to Mars' surface within 10–20 years. 

July 2011: Donated US$250,000 to Japan
 In July 2011, the Musk Foundation donated US$250,000 towards a solar power project in Sōma, Japan, a city that had been recently devastated by a tsunami.

2012: Announced SolarCity and Tesla Collaboration
The underlying motivation for funding both SolarCity and Tesla was to help combat global warming. In 2012, Musk announced that SolarCity and Tesla are collaborating to use electric vehicle batteries to smooth the impact of rooftop solar on the power grid, with the program going live in 2013.

May 25, 2012: SpaceX's vehicle docked with ISS for the first time        
On May 25, 2012, the SpaceX's vehicle, Dragon docked with the International Space Station (ISS), making history as the first commercial company to launch and berth a vehicle to the International Space Station.

2013: SolarCity became the second largest solar power provider         
By 2013, SolarCity was the second largest provider of solar power systems in the United States.

May 2013: Withdrew his support on the U.S. political action committee (PAC)
Musk had been a supporter of the U.S. political action committee (PAC) FWD.us, which was started by fellow high-profile entrepreneur Mark Zuckerberg and advocates for immigration reform. However, in May 2013, Musk publicly withdrew his support in protest of advertisements the PAC was running that supported causes like the Keystone Pipeline. Musk and other members, including David O. Sacks, pulled out, criticizing the strategy as "cynical." Musk further stated, "we shouldn't give in to the politics. If we give in to that, we'll get the political system we deserve."

August 12, 2013: Unveiled a concept for a high-speed transportation system
On August 12, 2013, Musk unveiled a concept for a high-speed transportation system incorporating reduced-pressure tubes in which pressurized capsules ride on an air cushion driven by linear induction motors and air compressors. The mechanism for releasing the concept was an alpha-design document that, in addition to scoping out the technology, outlined a notional route where such a transport system might be built: between the Greater Los Angeles Area and the San Francisco Bay Area.

2014: Announced Open-Sourcing Tesla Technology          
In 2014, Musk announced that Tesla would allow its technology patents to be used by anyone in good faith in a bid to entice automobile manufacturers to speed up development of electric cars.

June 17, 2014: Committed to building a SolarCity advanced production facility in Buffalo          
On June 17, 2014, Musk committed to building a SolarCity advanced production facility in Buffalo, New York, that would triple the size of the largest solar plant in the United States. Musk stated the plant will be "one of the single largest solar panel production plants in the world," and it will be followed by one or more even bigger facilities in subsequent years. The Tesla Gigafactory 2 is a photovoltaic (PV) cell factory, leased by Tesla subsidiary SolarCity in Buffalo, New York. Construction on the factory started in 2014 and was completed in 2017.

January 2015: Made a cameo in The Simpsons episode    
In January 2015, Musk made a guest appearance playing himself on The Simpsons in an episode titled "The Musk Who Fell to Earth"; the episode poked fun at many of Musk's ideas.

January 2015: Donated US$10 million to the Future of Life Institute          
Musk donated US$10 million to the Future of Life Institute in January 2015, to run a global research program aimed at keeping artificial intelligence beneficial to humanity.

June 2015: Announced Hyperloop design competition     
In June 2015, Musk announced a design competition for students and others to build Hyperloop pods to operate on a SpaceX-sponsored mile-long track in a 2015–2017 Hyperloop pod competition. The track was used in January 2017, and Musk also started building a tunnel. 

November 2015: Made a cameo in The Big Bang Theory episode      
In November 2015, Musk appeared in an episode of The Big Bang Theory, playing himself, volunteering at a soup kitchen with Wolowitz.

December 2015: Announced creation on OpenAi, Artificial Intelligence company     
In December 2015, Musk announced the creation of OpenAI, a not-for-profit artificial intelligence (AI) research company. OpenAI aims to develop artificial general intelligence in a way that is safe and beneficial to humanity.

2016: Dating, SolarCity Acquisition, Neuralink    
Musk began dating American actress Amber Heard in 2016 but the two split up after one year due to their conflicting schedules. 
SolarCity was acquired by Tesla, Inc. in 2016 and is currently a wholly owned subsidiary of Tesla.
In 2016, Musk co-founded Neuralink, a neurotechnology startup company to integrate the human brain with artificial intelligence. 
Musk appeared as himself in the romantic comedy film Why Him? where he was briefly met by one of the main characters, Ned Flemming played by Bryan Cranston, in a bar at a party.
Also in 2016, Musk was referenced by Dr. Martin Stein on The CW time-travel TV show DC's Legends of Tomorrow. During time travel to the past, Stein meets his younger self and introduced himself as Elon Musk, to disguise his own identity.
By 2016, Musk's private trust holds 54% of SpaceX stock, equivalent to 78% of voting shares.

September 2016: Revealed Mars colonization exploration architecture details
In September 2016, Musk revealed details of his architecture to explore and colonize Mars. 

May 12, 2017: Hyperloop One announced first successful test run  
Hyperloop One, a company participating in Hyperloop competition, had announced that it had done its first successful test run on its DevLoop track in Nevada on July 13, 2017. It lasted 5.3 seconds, reaching a top speed of 70 mph.

July 2017: Purchased x.com domain from PayPal   
In July 2017, Musk purchased the domain x.com from PayPal for an undisclosed amount, stating that it has sentimental value to him.

2018: Left the OpenAI board  
In 2018 Musk left the OpenAI board to avoid possible future conflicts with his role as CEO of Tesla as Tesla increasingly becomes involved in AI.

May 7, 2018: Musk and Grimes announced that they were dating       
On May 7, 2018, Musk and Canadian musician Grimes revealed that they had begun dating.

July 2018: Attempted to provide assistance to rescuers during the Tham Luang cave rescue    
In July 2018, Musk attempted to provide assistance to rescuers during the Tham Luang cave rescue by ordering his employees to build a small rescue pod.  Thai authorities decided not to use the submarine, describing it as technologically impressive but impractical

September 2018: Charged by the U.S Exchange Commission for a false tweet on taking Tesla private       
In September 2018, Musk was charged by the U.S. Securities and Exchange Commission for a tweet claiming that funding had been secured for taking Tesla private. The lawsuit characterized the tweet as false, misleading, and damaging to investors. As a result, Musk and Tesla were fined $20 million each, and Musk was forced to step down as Tesla chairman within 45 days while remaining Tesla's CEO. Musk also proclaimed in several interviews since that he does not regret sending the tweet that triggered the SEC investigation. According to Reuters, Musk said the tweet that cost him and the company $20 million in fines was "Worth It". 

September 2018: Warned about the dangers of AI          
In an interview with Joe Rogan in September 2018, Musk warned about the dangers of developing artificial intelligence indiscriminately. 

September 2018: Appeared puffing from a cannabis-laced cigarette       
In mid-September 2018, Musk appeared on The Joe Rogan Experience podcast and discussed various topics for 21/2 hours. Within five days, the appearance had registered 10 million YouTube views. One of the highest profile and controversial aspects of the program was Musk's puffing from a cannabis-laced cigarette offered by Rogan. The Washington Post observed, "In the media's hands, it became a story about Musk's growing instability ..." Tesla stock dropped after the incident, which coincided with the confirmation of the departure of Tesla's Vice President of Worldwide Finance earlier that day. Fortune wondered if the cannabis use could have ramifications for SpaceX contracts with the United States Air Force, though a USAF spokesperson told The Verge that there was no investigation being carried out and that the Air Force is still processing the situation.

October 2018: Donated over $480,000 to install new water fountains at all Flint, Michigan schools. 
In October 2018, in an effort to help solve the Flint water crisis, Musk and the Musk Foundation donated over $480,000 to install new water fountains with filtration systems for access to clean water at all Flint, Michigan schools.

October 2018: Filed an 'intent to use' trademark application for Teslaquila    
Musk first mentioned Teslaquila in an April Fools tweet in 2018. The proposed Tesla-branded tequila become closer to a reality in October 2018 as Tesla filed an 'intent to use' trademark application with the U.S. Patent and Trademark Office. The trademark is for distilled agave liquor. Musk reaffirmed his intention to release the product with a tweet, featuring a mockup of the bottle, on October 12.

January 2019: Traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory   
In January 2019, Musk traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory, which is the company's first large-scale plant outside the U.S. Part of his visit to China, Musk also met the Chinese premier Li Keqiang. During their exchange, Musk confessed his love for China and wished he could visit China more often, to which the Chinese premier was quoted as saying "We can issue you a Chinese green card if that helps."

**Comment by AlexanderTirik** [comment]
June 28, 1971: Born in Pretoria, South Africa  
Musk was born on June 28, 1971, in Pretoria, South Africa. He is the son of Maye Musk, a model and dietitian from Regina, Saskatchewan, Canada, and Errol Musk, a South African electromechanical engineer, pilot and sailor.

1980: Parents Divorce          
His parents were divorced in 1980.

1981: Interest in Computing 
At the age of 10, he developed an interest in computing with the Commodore VIC-20 and taught himself computer programming. 

1983: Sold his first video game, Blastar          
By the age of 12, Musk sold the code of a BASIC-based video game he created called Blastar, to a magazine called PC and Office Technology, for approximately $500.

June 1989: Moved to Canada to attend Queen's University        
At the age of 17, in June 1989, Elon Musk moved to Canada to attend Queen's University, avoiding mandatory service in the South African military. His plan was to go United States where he thought great things are possible, more than any other country. And it would be easy to get to the United States from Canada.

1992: Went to University of Pennsylvania to Study Business and Physics          
He left Queen's University in 1992 to study business and physics at the University of Pennsylvania, and graduated with an undergraduate degree in economics and stayed for a second bachelor's degree in physics.

1995: Started Zip2, a Web Software Company
In 1995, Musk and his brother, Kimbal, started Zip2, a web software company which developed and marketed an Internet city guide for the newspaper publishing industry. The company raised  money from a small group of angel investors.

February 1999: Sold Zip2 to Compaq for US$307 million           
Compaq acquired Zip2 for US$307 million in cash and US$34 million in stock options in February 1999. Musk received US$22 million for his 7 percent share from the sale.

March 1999: Cofounded X.com, a financial service and payment company         
In March 1999, Musk co-founded X.com, an online financial services and e-mail payment company, with US$10 million from the sale of Zip2.

2000: X.com merged with Confinity to form PayPal, Musk married his first wife
X.com merged with Confinity, which had a money-transfer service called PayPal and Musk became the CEO and company's largest shareholder by owning 11.7% of shares. The merged company focused on the PayPal service and was later renamed PayPal. PayPal's early growth was driven mainly by a viral marketing campaign where new customers were recruited when they received money through the service.
Musk met his first wife, Canadian author Justine Wilson, while both were students at Ontario's Queen's University. They married in 2000. Their first son, Nevada Alexander Musk, died of sudden infant death syndrome (SIDS) at the age of 10 weeks.

October 2000: Musk got Fired from PayPal          
Musk was ousted in October 2000 from his role as CEO of PayPal (although he remained on the board) due to disagreements with other company leadership, notably over his desire to move PayPal's Unix-based infrastructure to Microsoft Windows. 

2001: Interest in Space Exploration          
In 2001, Musk conceptualized Mars Oasis, a project to land a miniature experimental greenhouse on Mars, containing food crops growing on Martian regolith, in an attempt to regain public interest in space exploration. 

October 2001: Went to Moscow to buy ICBMs to send payloads to Mars          
In October 2001, Musk travelled to Moscow with Jim Cantrell (an aerospace supplies fixer), and Adeo Ressi (his best friend from college), to buy refurbished Dnepr Intercontinental ballistic missiles (ICBMs) that could send the envisioned payloads into space. The group met with companies such as NPO Lavochkin and Kosmotras; however, according to Cantrell, Musk was seen as a novice and was consequently spat on by one of the Russian chief designers, and the group returned to the United States empty-handed.

February 2002: Got an idea to build affordable Rockets          
In February 2002, the group returned to Russia to look for three ICBMs, bringing along Mike Griffin. Griffin had worked for the CIA's venture capital arm, In-Q-Tel, as well as NASA's Jet Propulsion Laboratory, and was just leaving Orbital Sciences, a maker of satellites and spacecraft. The group met again with Kosmotras, and were offered one rocket for US$8 million; however, this was seen by Musk as too expensive; Musk consequently stormed out of the meeting. On the flight back from Moscow, Musk realized that he could start a company that could build the affordable rockets he needed.

May 2002: Founded SpaceX, a space exploration company 
Musk founded Space Exploration Technologies, or SpaceX, in May 2002 with US$100 million of his early fortune. Musk became the chief executive officer (CEO) and chief technology officer (CTO). SpaceX develops and manufactures space launch vehicles with a focus on advancing the state of rocket technology. 

October 2002: eBay acquired PayPal
In October 2002, PayPal was acquired by eBay for US$1.5 billion in stock, of which Musk received US$165 million. 

July 2003: Tesla, Inc was incorporated
Tesla, Inc. (originally Tesla Motors) was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning, who financed the company until the Series A round of funding.

2004: Musk's wife gave birth to twin sons
Musk and his wife had 2 sons, twins, through in vitro fertilization.

February 2004: Musk joined Tesla
Musk led the Series A round of investment for Tesla in February 2004, joined Tesla's board of directors as its chairman. 

2006: Musk's wife gave birth to triplets, Cofounded SolarCity and SpaceX Success
Musk and his wife had other 3 sons, triplets, through in vitro fertilization.
Musk provided the initial concept and financial capital for SolarCity, which was then co-founded in 2006 by his cousins Lyndon and Peter Rive.
From 2006, SpaceX got various contracts from NASA to transport cargo and astronauts to the International Space Station.

2007: Musk became the CEO of Tesla
Following the financial crisis in 2008 and after a series of escalating conflicts in 2007, Eberhard was ousted from the firm. Musk assumed leadership of the company as CEO and product architect.

2008: Musk and Wife, Justine Separated
Musk and his wife Justine were separated. They share custody of their five sons.
December 2015: Announced creation on OpenAi, Artificial Intelligence company   
In December 2015, Musk announced the creation of OpenAI, a not-for-profit artificial intelligence (AI) research company. OpenAI aims to develop artificial general intelligence in a way that is safe and beneficial to humanity.  

2016: Dating, SolarCity Acquisition, Neuralink           
Musk began dating American actress Amber Heard in 2016 but the two split up after one year due to their conflicting schedules. 
SolarCity was acquired by Tesla, Inc. in 2016 and is currently a wholly owned subsidiary of Tesla.
In 2016, Musk co-founded Neuralink, a neurotechnology startup company to integrate the human brain with artificial intelligence. 
Musk appeared as himself in the romantic comedy film Why Him? where he was briefly met by one of the main characters, Ned Flemming played by Bryan Cranston, in a bar at a party.
Also in 2016, Musk was referenced by Dr. Martin Stein on The CW time-travel TV show DC's Legends of Tomorrow. During time travel to the past, Stein meets his younger self and introduced himself as Elon Musk, to disguise his own identity.
By 2016, Musk's private trust holds 54% of SpaceX stock, equivalent to 78% of voting shares.

September 2016: Revealed Mars colonization exploration architecture details
In September 2016, Musk revealed details of his architecture to explore and colonize Mars. 

May 12, 2017: Hyperloop One announced first successful test run  
Hyperloop One, a company participating in Hyperloop competition, had announced that it had done its first successful test run on its DevLoop track in Nevada on July 13, 2017. It lasted 5.3 seconds, reaching a top speed of 70 mph.

July 2017: Purchased x.com domain from PayPal          
In July 2017, Musk purchased the domain x.com from PayPal for an undisclosed amount, stating that it has sentimental value to him.

2018: Left the OpenAI board           
In 2018 Musk left the OpenAI board to avoid possible future conflicts with his role as CEO of Tesla as Tesla increasingly becomes involved in AI.

May 7, 2018: Musk and Grimes announced that they were dating    
On May 7, 2018, Musk and Canadian musician Grimes revealed that they had begun dating.

July 2018: Attempted to provide assistance to rescuers during the Tham Luang cave rescue
In July 2018, Musk attempted to provide assistance to rescuers during the Tham Luang cave rescue by ordering his employees to build a small rescue pod.  Thai authorities decided not to use the submarine, describing it as technologically impressive but impractical

September 2018: Charged by the U.S Exchange Commission for a false tweet on taking Tesla private       
In September 2018, Musk was charged by the U.S. Securities and Exchange Commission for a tweet claiming that funding had been secured for taking Tesla private. The lawsuit characterized the tweet as false, misleading, and damaging to investors. As a result, Musk and Tesla were fined $20 million each, and Musk was forced to step down as Tesla chairman within 45 days while remaining Tesla's CEO. Musk also proclaimed in several interviews since that he does not regret sending the tweet that triggered the SEC investigation. According to Reuters, Musk said the tweet that cost him and the company $20 million in fines was "Worth It". 

September 2018: Warned about the dangers of AI          
In an interview with Joe Rogan in September 2018, Musk warned about the dangers of developing artificial intelligence indiscriminately. 

September 2018: Appeared puffing from a cannabis-laced cigarette        
In mid-September 2018, Musk appeared on The Joe Rogan Experience podcast and discussed various topics for 21/2 hours. Within five days, the appearance had registered 10 million YouTube views. One of the highest profile and controversial aspects of the program was Musk's puffing from a cannabis-laced cigarette offered by Rogan. The Washington Post observed, "In the media's hands, it became a story about Musk's growing instability ..." Tesla stock dropped after the incident, which coincided with the confirmation of the departure of Tesla's Vice President of Worldwide Finance earlier that day. Fortune wondered if the cannabis use could have ramifications for SpaceX contracts with the United States Air Force, though a USAF spokesperson told The Verge that there was no investigation being carried out and that the Air Force is still processing the situation.

October 2018: Donated over $480,000 to install new water fountains at all Flint, Michigan schools.          
In October 2018, in an effort to help solve the Flint water crisis, Musk and the Musk Foundation donated over $480,000 to install new water fountains with filtration systems for access to clean water at all Flint, Michigan schools.

October 2018: Filed an 'intent to use' trademark application for Teslaquila          
Musk first mentioned Teslaquila in an April Fools tweet in 2018. The proposed Tesla-branded tequila become closer to a reality in October 2018 as Tesla filed an 'intent to use' trademark application with the U.S. Patent and Trademark Office. The trademark is for distilled agave liquor. Musk reaffirmed his intention to release the product with a tweet, featuring a mockup of the bottle, on October 12.

January 2019: Traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory   
In January 2019, Musk traveled to China for the groundbreaking of Tesla's Shanghai Gigafactory, which is the company's first large-scale plant outside the U.S. Part of his visit to China, Musk also met the Chinese premier Li Keqiang. During their exchange, Musk confessed his love for China and wished he could visit China more often, to which the Chinese premier was quoted as saying "We can issue you a Chinese green card if that helps."
